package mx.gob.cnpss_dgao;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-01-16T11:32:08.552-06:00
 * Generated source version: 3.0.4
 * 
 */
@WebService(targetNamespace = "http://www.cnpss-dgao.gob.mx/", name = "wspSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WspSoap {

    @WebResult(name = "consultaDatosResult", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
    @RequestWrapper(localName = "consultaDatos", targetNamespace = "http://www.cnpss-dgao.gob.mx/", className = "mx.gob.cnpss_dgao.ConsultaDatos")
    @WebMethod(action = "http://www.cnpss-dgao.gob.mx/consultaDatos")
    @ResponseWrapper(localName = "consultaDatosResponse", targetNamespace = "http://www.cnpss-dgao.gob.mx/", className = "mx.gob.cnpss_dgao.ConsultaDatosResponse")
    public java.lang.String consultaDatos(
        @WebParam(name = "Folio", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
        java.lang.String folio,
        @WebParam(name = "Curp", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
        java.lang.String curp,
        @WebParam(name = "Nombre", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
        java.lang.String nombre,
        @WebParam(name = "A_Paterno", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
        java.lang.String aPaterno,
        @WebParam(name = "A_Materno", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
        java.lang.String aMaterno,
        @WebParam(name = "Fecha_Nacimiento", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
        java.lang.String fechaNacimiento,
        @WebParam(name = "Lugar_Nacimiento", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
        java.lang.String lugarNacimiento,
        @WebParam(name = "Usuario", targetNamespace = "http://www.cnpss-dgao.gob.mx/")
        java.lang.String usuario
    );
}
