
package mx.gob.cnpss_dgao;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.4
 * 2017-01-16T11:32:08.479-06:00
 * Generated source version: 3.0.4
 * 
 */
public final class WspSoap_WspSoap12_Client {

    private static final QName SERVICE_NAME = new QName("http://www.cnpss-dgao.gob.mx/", "wsp");

    private WspSoap_WspSoap12_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Wsp.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Wsp ss = new Wsp(wsdlURL, SERVICE_NAME);
        WspSoap port = ss.getWspSoap12();  
        
        {
        System.out.println("Invoking consultaDatos...");
        java.lang.String _consultaDatos_folio = "";
        java.lang.String _consultaDatos_curp = "";
        java.lang.String _consultaDatos_nombre = "";
        java.lang.String _consultaDatos_aPaterno = "";
        java.lang.String _consultaDatos_aMaterno = "";
        java.lang.String _consultaDatos_fechaNacimiento = "";
        java.lang.String _consultaDatos_lugarNacimiento = "";
        java.lang.String _consultaDatos_usuario = "";
        java.lang.String _consultaDatos__return = port.consultaDatos(_consultaDatos_folio, _consultaDatos_curp, _consultaDatos_nombre, _consultaDatos_aPaterno, _consultaDatos_aMaterno, _consultaDatos_fechaNacimiento, _consultaDatos_lugarNacimiento, _consultaDatos_usuario);
        System.out.println("consultaDatos.result=" + _consultaDatos__return);


        }

        System.exit(0);
    }

}
